apiVersion: apps/v1
kind: Deployment
metadata:
  name: amtoolkit
  namespace: amtoolkit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amtoolkit-app
  template:
    metadata:
      labels:
        app: amtoolkit-app
    spec:
      containers:
      - name: amtoolkit-app
        image: image-name:image-tag
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: amtoolkit
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: amtoolkit-app
  type: ClusterIP
